# bridge.py — pcbpilot's KiCad bridge. Run with KiCad's bundled Python
# (the one that can `import pcbnew`). Embedded into the pcbpilot binary
# (internal/kicad, go:embed) and written to a cache file before each run.
#
# Every subcommand prints exactly one result line on stdout:
#
#     PCBPILOT_JSON:{...}
#
# pcbnew prints debug noise (wx asserts) on stderr and occasionally on
# stdout, so the Go side reads only the line with that prefix. A failure is
# {"ok": false, "error": "..."} with exit status 1.
#
# Units: every length in the output is mil, y-UP (y = -y_kicad), to match
# pcbpilot's board snapshot (internal/app/pcb_board_snapshot.go). Rotations
# stay in degrees CCW (negating y keeps the visual sense of a rotation).
# Copper layer ids follow pcbpilot's EasyEDA numbering so the existing
# gates work unchanged: F.Cu = 1, B.Cu = 2, InN.Cu = 14+N, through-hole = 12.
#
# Only KiCad's public Python API (pcbnew) is used.
#
# Subcommands:
#   snapshot PCB                    board snapshot JSON (result.snapshot)
#   netclasses PCB REQS.json OUT    write intent widths/clearances as netclasses
#   ripup PCB OUT                   delete unlocked tracks and vias
#   dsn PCB OUT.dsn                 ExportSpecctraDSN
#   ses PCB IN.ses OUT.kicad_pcb    ImportSpecctraSES + zone fill + save
#   fill PCB                        zone fill + save in place

import json
import math
import os
import re
import shutil
import sys

import pcbnew

PREFIX = "PCBPILOT_JSON:"
NM_PER_MIL = 25400.0
CLASS_PREFIX = "PP"
DRU_BEGIN = "# pcbpilot:begin (generated by pcbpilot kicad netclasses; do not edit inside this block)"
DRU_END = "# pcbpilot:end"


def emit(obj, code=0):
    sys.stdout.write("\n" + PREFIX + json.dumps(obj, separators=(",", ":")) + "\n")
    sys.stdout.flush()
    sys.exit(code)


def mil(v):
    return round(v / NM_PER_MIL, 4)


def xy(p):
    return mil(p.x), mil(-p.y)


INNER = {}


def layer_id(board, layer):
    """pcbpilot copper layer id of a KiCad layer (0 = not copper)."""
    if layer == pcbnew.F_Cu:
        return 1
    if layer == pcbnew.B_Cu:
        return 2
    if not INNER:
        for k in range(1, 31):
            v = getattr(pcbnew, "In%d_Cu" % k, None)
            if v is not None:
                INNER[v] = 14 + k
    return INNER.get(layer, 0)


def kicad_layer_name(layer):
    try:
        return pcbnew.LayerName(layer)
    except Exception:
        return str(layer)


def chain_points(chain):
    pts = []
    for i in range(chain.PointCount()):
        p = chain.CPoint(i)
        pts.append([mil(p.x), mil(-p.y)])
    return pts


def source_of(points):
    """EasyEDA-style polygon source [x, y, "L", x, y, ...] (mil, y-up)."""
    if not points:
        return []
    out = [points[0][0], points[0][1], "L"]
    for p in points[1:]:
        out += [p[0], p[1]]
    return out


def bbox_of(points):
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    return {"minX": min(xs), "minY": min(ys), "maxX": max(xs), "maxY": max(ys)}


def box_mil(box):
    # KiCad BOX2I (y-down) → y-up mil bbox.
    x0, y0 = box.GetX(), box.GetY()
    x1, y1 = x0 + box.GetWidth(), y0 + box.GetHeight()
    return {"minX": mil(x0), "minY": mil(-y1), "maxX": mil(x1), "maxY": mil(-y0)}


def poly_set_fills(ps):
    """One fill per outline: [outline contour, hole contours...] (even-odd)."""
    fills = []
    for i in range(ps.OutlineCount()):
        contours = [source_of(chain_points(ps.Outline(i)))]
        for j in range(ps.HoleCount(i)):
            contours.append(source_of(chain_points(ps.Hole(i, j))))
        fills.append({"source": contours})
    return fills


def lcsc_of(fp):
    want = {"lcsc", "lcsc part", "lcsc part #", "jlcpcb part #", "jlcpcb part", "lcsc#"}
    for f in fp.GetFields():
        if f.GetName().strip().lower() in want and f.GetText().strip():
            return f.GetText().strip()
    return ""


PAD_KIND = {}


def pad_kind(shape):
    if not PAD_KIND:
        PAD_KIND.update({
            pcbnew.PAD_SHAPE_RECT: "RECT",
            pcbnew.PAD_SHAPE_ROUNDRECT: "RECT",
            pcbnew.PAD_SHAPE_CHAMFERED_RECT: "RECT",
            pcbnew.PAD_SHAPE_TRAPEZOID: "RECT",
            pcbnew.PAD_SHAPE_CIRCLE: "ELLIPSE",
            pcbnew.PAD_SHAPE_OVAL: "OVAL",
            pcbnew.PAD_SHAPE_CUSTOM: "POLYGON",
        })
    return PAD_KIND.get(shape, "POLYGON")


def snapshot(board):
    snap = {"components": [], "partial": [], "source": "kicad"}
    notes = snap["partial"]
    holes = []
    for fp in board.GetFootprints():
        ref = fp.GetReference()
        x, y = xy(fp.GetPosition())
        comp = {
            "primitiveId": fp.m_Uuid.AsString(),
            "designator": ref,
            "name": fp.GetValue(),
            "device": fp.GetValue(),
            "value": fp.GetValue(),
            "footprint": fp.GetFPIDAsString(),
            "layer": 2 if fp.IsFlipped() else 1,
            "side": "bottom" if fp.IsFlipped() else "top",
            "x": x,
            "y": y,
            "rotation": round(fp.GetOrientationDegrees() % 360.0, 6),
            "locked": bool(fp.IsLocked()),
            "bbox": box_mil(fp.GetBoundingBox(False)),
            "pads": [],
        }
        lcsc = lcsc_of(fp)
        if lcsc:
            comp["lcsc"] = lcsc
        for p in fp.Pads():
            attr = p.GetAttribute()
            px, py = xy(p.GetPosition())
            size = p.GetSize(pcbnew.F_Cu) if hasattr(p, "GetSize") else p.GetSize()
            drill = p.GetDrillSize()
            if attr == pcbnew.PAD_ATTRIB_NPTH:
                hole = {"owner": ref, "componentId": comp["primitiveId"], "sourceId": p.m_Uuid.AsString(), "x": px, "y": py}
                if drill.x == drill.y:
                    hole["shape"], hole["dia"] = "circle", mil(drill.x)
                else:
                    # Slot: its bounding box as a conservative envelope.
                    poly = chain_points(p.GetEffectiveHoleShape().Outline(0)) if hasattr(p.GetEffectiveHoleShape(), "Outline") else []
                    if len(poly) < 3:
                        r = mil(max(drill.x, drill.y)) / 2
                        poly = [[px - r, py - r], [px + r, py - r], [px + r, py + r], [px - r, py + r]]
                    hole["shape"], hole["points"], hole["envelope"] = "polygon", poly, True
                holes.append(hole)
                continue
            if attr == pcbnew.PAD_ATTRIB_PTH:
                lid = 12
            elif p.IsOnLayer(pcbnew.F_Cu):
                lid = 1
            elif p.IsOnLayer(pcbnew.B_Cu):
                lid = 2
            else:
                continue  # no copper (fiducial on mask only, etc.)
            bb = box_mil(p.GetBoundingBox())
            kind = pad_kind(p.GetShape(pcbnew.F_Cu))
            w, h, rot = mil(size.x), mil(size.y), round(p.GetOrientationDegrees() % 360.0, 6)
            if kind == "POLYGON":
                w, h, rot = bb["maxX"] - bb["minX"], bb["maxY"] - bb["minY"], 0.0
            pad = {
                "primitiveId": p.m_Uuid.AsString(),
                "padNumber": p.GetNumber(),
                "net": p.GetNetname(),
                "layer": lid,
                "x": px,
                "y": py,
                "width": round(bb["maxX"] - bb["minX"], 4),
                "height": round(bb["maxY"] - bb["minY"], 4),
                "rotation": rot,
                "shape": [kind, w, h],
            }
            if lid == 12:
                pad["holeDiameter"] = mil(min(drill.x, drill.y))
            comp["pads"].append(pad)
        snap["components"].append(comp)
    if holes:
        snap["footprintHoles"] = holes

    # Board outline (Edge.Cuts); arcs are approximated by KiCad.
    ps = pcbnew.SHAPE_POLY_SET()
    ok = False
    try:
        ok = board.GetBoardPolygonOutlines(ps, False)
    except TypeError:
        ok = board.GetBoardPolygonOutlines(ps)
    fills = []
    if ok and ps.OutlineCount() > 0:
        best, area = 0, -1.0
        for i in range(ps.OutlineCount()):
            a = abs(ps.Outline(i).Area())
            if a > area:
                best, area = i, a
        pts = chain_points(ps.Outline(best))
        fmt = "polyline" if ps.OutlineCount() == 1 else "largest-of:%d" % ps.OutlineCount()
        snap["outline"] = {"bbox": bbox_of(pts), "points": pts, "source": "polygon", "format": fmt}
        for j in range(ps.HoleCount(best)):
            hp = chain_points(ps.Hole(best, j))
            fills.append({"primitiveId": "edgecut-%d" % j, "layer": 12, "net": "", "source": source_of(hp), "bbox": bbox_of(hp), "geometryAvailable": True})
    else:
        bb = board.GetBoardEdgesBoundingBox()
        if bb.GetWidth() > 0:
            snap["outline"] = {"bbox": box_mil(bb), "source": "bbox", "format": "no-closed-edge-cuts"}
        notes.append("board outline: Edge.Cuts is not one closed polygon — edge distances use the AABB")

    n = board.GetCopperLayerCount()
    snap["copperLayers"] = n
    ds = board.GetDesignSettings()
    dn = ds.m_NetSettings.GetDefaultNetclass()
    clr = max(ds.m_MinClearance, dn.GetClearance())
    snap["rules"] = {
        "clearanceMil": mil(clr),
        "clearanceTrackTrackMil": mil(clr),
        "trackWidthMil": mil(dn.GetTrackWidth()),
        "powerWidthMil": mil(dn.GetTrackWidth()),
        "trackWidthMinMil": mil(ds.m_TrackMinWidth),
        "viaDrillMil": mil(dn.GetViaDrill()),
        "viaDiameterMil": mil(dn.GetViaDiameter()),
        "copperToEdgeMil": mil(ds.m_CopperEdgeClearance),
        "holeToHoleMil": mil(ds.m_HoleToHoleMin),
        "source": "kicad",
    }
    classes = []
    for name, nc in ds.m_NetSettings.GetNetclasses().items():
        classes.append({"name": str(name), "trackWidthMil": mil(nc.GetTrackWidth()) if nc.HasTrackWidth() else None,
                        "clearanceMil": mil(nc.GetClearance()) if nc.HasClearance() else None})
    snap["netclasses"] = sorted(classes, key=lambda c: c["name"])
    nets = {}
    for name, net in board.GetNetsByName().items():
        name = str(name)
        if not name:
            continue
        try:
            nets[name] = ds.m_NetSettings.GetEffectiveNetClass(name).GetName()
        except Exception:
            nets[name] = ""
    snap["netClassOf"] = nets
    layer_types = {}
    for l in board.GetEnabledLayers().CuStack():
        layer_types[str(layer_id(board, l))] = {"name": kicad_layer_name(l), "type": int(board.GetLayerType(l))}
    snap["kicadLayers"] = layer_types

    lines, arcs, vias = [], [], []
    for t in board.GetTracks():
        tt = t.Type()
        if tt == pcbnew.PCB_VIA_T:
            vx, vy = xy(t.GetPosition())
            vias.append({"primitiveId": t.m_Uuid.AsString(), "net": t.GetNetname(), "x": vx, "y": vy,
                         "diameter": mil(t.GetWidth(pcbnew.F_Cu) if t.GetViaType() == pcbnew.VIATYPE_THROUGH else t.GetFrontWidth()),
                         "holeDiameter": mil(t.GetDrillValue()), "locked": bool(t.IsLocked()),
                         "fromLayer": layer_id(board, t.TopLayer()), "toLayer": layer_id(board, t.BottomLayer())})
            continue
        lid = layer_id(board, t.GetLayer())
        sx, sy = xy(t.GetStart())
        ex, ey = xy(t.GetEnd())
        rec = {"primitiveId": t.m_Uuid.AsString(), "net": t.GetNetname(), "layer": lid,
               "startX": sx, "startY": sy, "endX": ex, "endY": ey, "lineWidth": mil(t.GetWidth()), "locked": bool(t.IsLocked())}
        if tt == pcbnew.PCB_ARC_T:
            mx, my = xy(t.GetMid())
            rec["midX"], rec["midY"] = mx, my
            rec["arcAngle"] = arc_angle((sx, sy), (mx, my), (ex, ey))
            arcs.append(rec)
        else:
            lines.append(rec)
    pours, poured, regions = [], [], []
    for z in board.Zones():
        zid = z.m_Uuid.AsString()
        layers = [l for l in z.GetLayerSet().CuStack()]
        outline = []
        if z.Outline().OutlineCount() > 0:
            outline = chain_points(z.Outline().Outline(0))
        if z.GetIsRuleArea():
            rules = []
            if z.GetDoNotAllowFootprints():
                rules.append(2)
            if z.GetDoNotAllowTracks() or z.GetDoNotAllowVias():
                rules.append(5)
            if z.GetDoNotAllowZoneFills():
                rules.append(7)
            regions.append({"primitiveId": zid, "name": z.GetZoneName(), "layer": 12 if len(layers) != 1 else layer_id(board, layers[0]),
                            "layers": [layer_id(board, l) for l in layers], "ruleType": rules, "source": source_of(outline),
                            "bbox": bbox_of(outline) if outline else None, "geometryAvailable": bool(outline)})
            continue
        for l in layers:
            lid = layer_id(board, l)
            pours.append({"primitiveId": zid, "name": z.GetZoneName(), "net": z.GetNetname(), "layer": lid,
                          "source": source_of(outline), "geometryAvailable": bool(outline)})
            if z.IsFilled():
                f = poly_set_fills(z.GetFilledPolysList(l))
                if f:
                    poured.append({"pourPrimitiveId": zid, "net": z.GetNetname(), "layer": lid, "fills": f})
    snap["copper"] = {
        "availability": {k: "available" for k in ("routing", "vias", "pours", "poured", "regions", "fills")},
        "lines": lines, "arcs": arcs, "arcsAvailable": True, "vias": vias,
        "pours": pours, "poured": poured, "regions": regions, "fills": fills,
    }
    snap["routedLines"] = len(lines) + len(arcs)
    snap["partial"] = notes
    if not notes:
        del snap["partial"]
    return snap


def arc_angle(s, m, e):
    """Signed sweep (degrees, CCW > 0 in y-up) of the arc s→m→e."""
    ax, ay = s
    bx, by = m
    cx, cy = e
    d = 2 * (ax * (by - cy) + bx * (cy - ay) + cx * (ay - by))
    if abs(d) < 1e-12:
        return 0.0
    ux = ((ax * ax + ay * ay) * (by - cy) + (bx * bx + by * by) * (cy - ay) + (cx * cx + cy * cy) * (ay - by)) / d
    uy = ((ax * ax + ay * ay) * (cx - bx) + (bx * bx + by * by) * (ax - cx) + (cx * cx + cy * cy) * (bx - ax)) / d
    a0 = math.atan2(ay - uy, ax - ux)
    a1 = math.atan2(by - uy, bx - ux)
    a2 = math.atan2(cy - uy, cx - ux)

    def ccw(a, b):
        return (b - a) % (2 * math.pi)

    sweep = ccw(a0, a2)
    if ccw(a0, a1) > sweep:  # the mid point is not on the CCW path: clockwise
        sweep -= 2 * math.pi
    return round(math.degrees(sweep), 6)


# ── netclasses ───────────────────────────────────────────────────────────────

def fmt_mil(v):
    s = ("%.2f" % v).rstrip("0").rstrip(".")
    return s.replace(".", "p")


def dru_path(pcb):
    return os.path.splitext(pcb)[0] + ".kicad_dru"


def save_board(board, src, out):
    """SaveBoard writes OUT.kicad_pro (and .kicad_prl) from the loaded project;
    the custom rules file is copied unless the caller wrote one."""
    if os.path.abspath(src) != os.path.abspath(out):
        # SaveBoard keeps an existing OUT.kicad_pro instead of writing the
        # loaded project's settings into it (probed on 10.0.6).
        for ext in (".kicad_pro", ".kicad_prl"):
            stale = os.path.splitext(out)[0] + ext
            if os.path.exists(stale):
                os.remove(stale)
    pcbnew.SaveBoard(out, board)
    if os.path.abspath(src) != os.path.abspath(out) and os.path.exists(dru_path(src)) and not os.path.exists(dru_path(out)):
        shutil.copyfile(dru_path(src), dru_path(out))


def netclasses(pcb, reqs_path, out):
    with open(reqs_path) as f:
        reqs = json.load(f)
    board = pcbnew.LoadBoard(pcb)
    ns = board.GetDesignSettings().m_NetSettings

    # Idempotent: drop classes and patterns of an earlier run.
    old = [str(n) for n in ns.GetNetclasses().keys() if re.match(r"^%s\d+_" % CLASS_PREFIX, str(n))]
    if old:
        keep = {}
        for n, nc in ns.GetNetclasses().items():
            if str(n) not in old:
                keep[str(n)] = nc
        pats = []
        for item in list_patterns(pcb):
            if item[1] not in old:
                pats.append(item)
        ns.ClearNetclasses()
        for n, nc in keep.items():
            ns.SetNetclass(n, nc)
        ns.ClearNetclassPatternAssignments()
        for p, c in pats:
            ns.SetNetclassPatternAssignment(p, c)
        ns.ClearAllCaches()

    names = {str(n) for n in board.GetNetsByName().keys()}
    missing, groups, raised = [], {}, []
    eps = 0.005
    for net in sorted(reqs):
        r = reqs[net]
        if net not in names:
            missing.append(net)
            continue
        eff = ns.GetEffectiveNetClass(net)
        have_w = mil(eff.GetTrackWidth()) if eff.HasTrackWidth() else 0.0
        have_c = mil(eff.GetClearance()) if eff.HasClearance() else 0.0
        outer = float(r.get("outerMil") or 0)
        inner = float(r.get("innerMil") or 0) or outer
        mn = float(r.get("minMil") or 0)
        clr = float(r.get("clearanceMil") or 0)
        w = max(outer, have_w)
        c = max(clr, have_c)
        if have_w > outer + eps:
            raised.append("%s: width kept at %s mil (class %s; intent %s)" % (net, have_w, eff.GetName(), outer))
        if have_c > clr + eps:
            raised.append("%s: clearance kept at %s mil (class %s; intent %s)" % (net, have_c, eff.GetName(), clr))
        key = (round(w, 2), round(inner, 2), round(mn, 2), round(c, 2), round(outer, 2))
        groups.setdefault(key, []).append(net)

    classes = []
    for i, key in enumerate(sorted(groups)):
        w, inner, mn, c, outer = key
        name = "%s%d_W%s" % (CLASS_PREFIX, i + 1, fmt_mil(w))
        nc = pcbnew.NETCLASS(name)
        nc.SetTrackWidth(int(round(w * NM_PER_MIL)))
        if c > 0:
            nc.SetClearance(int(round(c * NM_PER_MIL)))
        # Highest priority: our values win over any user class that also
        # matches the net (KiCad then builds a composite "PPn_...,User").
        nc.SetPriority(-1000000 + i)
        nc.SetDescription("pcbpilot intent: outer %s / inner %s / min %s / clearance %s mil" % (outer, inner, mn, c))
        ns.SetNetclass(name, nc)
        for net in groups[key]:
            ns.SetNetclassPatternAssignment(net, name)
        classes.append({"name": name, "nets": groups[key], "trackWidthMil": w, "innerWidthMil": inner,
                        "minMil": mn, "clearanceMil": c, "intentOuterMil": outer})
    ns.ClearAllCaches()
    board.SynchronizeNetsAndNetClasses(True)

    mismatched = []
    for cl in classes:
        for net in cl["nets"]:
            eff = ns.GetEffectiveNetClass(net)
            first = eff.GetName().split(",")[0]
            if first != cl["name"] or abs(mil(eff.GetTrackWidth()) - cl["trackWidthMil"]) > eps:
                mismatched.append("%s: effective class %s width %s mil" % (net, eff.GetName(), mil(eff.GetTrackWidth())))
            cl.setdefault("effective", {})[net] = eff.GetName()

    # Custom DRC rules: KiCad netclasses carry one width, so the inner width
    # becomes a (layer inner) track_width rule whose opt is the inner width
    # (KiCad's interactive router uses opt) and whose min is the intent's
    # minimum; every class with a minimum also gets an all-layer floor.
    src_dru = dru_path(pcb)
    text = ""
    if os.path.exists(src_dru):
        with open(src_dru) as f:
            text = f.read()
    text = re.sub(re.escape(DRU_BEGIN) + r".*?" + re.escape(DRU_END) + r"\n?", "", text, flags=re.S)
    rules = []
    for cl in classes:
        mm = lambda v: ("%.4f" % (v * 0.0254)).rstrip("0").rstrip(".")
        if cl["minMil"] > 0:
            rules.append('(rule "pcbpilot %s min"\n  (condition "A.hasNetclass(\'%s\')")\n  (constraint track_width (min %smm)))'
                         % (cl["name"], cl["name"], mm(cl["minMil"])))
        if cl["innerWidthMil"] > cl["trackWidthMil"] + eps:
            lo = cl["minMil"] if cl["minMil"] > 0 else mil(board.GetDesignSettings().m_TrackMinWidth)
            rules.append('(rule "pcbpilot %s inner"\n  (layer inner)\n  (condition "A.hasNetclass(\'%s\')")\n  (constraint track_width (min %smm) (opt %smm)))'
                         % (cl["name"], cl["name"], mm(lo), mm(cl["innerWidthMil"])))
    if rules:
        if not re.search(r"\(version\s+\d+\)", text):
            text = "(version 1)\n" + text
        text = text.rstrip("\n") + "\n" + DRU_BEGIN + "\n" + "\n".join(rules) + "\n" + DRU_END + "\n"
    out_dru = dru_path(out)
    if text.strip():
        with open(out_dru, "w") as f:
            f.write(text)
    elif os.path.exists(out_dru) and os.path.abspath(out_dru) != os.path.abspath(src_dru):
        os.remove(out_dru)
    save_board(board, pcb, out)
    return {"ok": True, "out": out, "classes": classes, "missingNets": missing, "kept": raised,
            "mismatched": mismatched, "dru": out_dru if text.strip() else "", "druRules": len(rules)}


def list_patterns(pcb):
    """(pattern, netclass) pairs of the project file next to PCB: the swig
    binding exposes NET_SETTINGS' pattern list only as an opaque object."""
    pro = os.path.splitext(pcb)[0] + ".kicad_pro"
    try:
        with open(pro) as f:
            ns = json.load(f).get("net_settings") or {}
    except (OSError, ValueError):
        return []
    return [(p.get("pattern", ""), p.get("netclass", "")) for p in ns.get("netclass_patterns") or [] if p.get("pattern")]


# ── routing round trip ───────────────────────────────────────────────────────

def counts(board):
    tr = vi = 0
    for t in board.GetTracks():
        if t.Type() == pcbnew.PCB_VIA_T:
            vi += 1
        else:
            tr += 1
    return {"tracks": tr, "vias": vi}


def fill_zones(board):
    zones = board.Zones()
    filler = pcbnew.ZONE_FILLER(board)
    filler.Fill(zones)
    return len(zones)


def ripup(pcb, out):
    board = pcbnew.LoadBoard(pcb)
    before = counts(board)
    dead = [t for t in board.GetTracks() if not t.IsLocked()]
    for t in dead:
        board.Remove(t)
    save_board(board, pcb, out)
    return {"ok": True, "out": out, "before": before, "after": counts(board), "removed": len(dead)}


def dsn(pcb, out):
    board = pcbnew.LoadBoard(pcb)
    ok = pcbnew.ExportSpecctraDSN(board, out)
    if not ok or not os.path.exists(out):
        return {"ok": False, "error": "ExportSpecctraDSN failed"}
    return {"ok": True, "out": out, "copperLayers": board.GetCopperLayerCount()}


def ses(pcb, ses_path, out):
    board = pcbnew.LoadBoard(pcb)
    before = counts(board)
    ok = pcbnew.ImportSpecctraSES(board, ses_path)
    if not ok:
        return {"ok": False, "error": "ImportSpecctraSES failed for " + ses_path}
    after = counts(board)
    zones = fill_zones(board)
    save_board(board, pcb, out)
    return {"ok": True, "out": out, "before": before, "after": after, "zonesFilled": zones}


def fill(pcb):
    board = pcbnew.LoadBoard(pcb)
    zones = fill_zones(board)
    pcbnew.SaveBoard(pcb, board)
    return {"ok": True, "out": pcb, "zonesFilled": zones}


def main(argv):
    usage = "usage: bridge.py snapshot PCB | netclasses PCB REQS OUT | ripup PCB OUT | dsn PCB OUT | ses PCB SES OUT | fill PCB"
    if len(argv) < 2:
        emit({"ok": False, "error": usage}, 2)
    cmd, args = argv[1], argv[2:]
    want = {"snapshot": 1, "netclasses": 3, "ripup": 2, "dsn": 2, "ses": 3, "fill": 1}
    if cmd not in want or len(args) != want[cmd]:
        emit({"ok": False, "error": usage}, 2)
    try:
        if cmd == "snapshot":
            board = pcbnew.LoadBoard(args[0])
            res = {"ok": True, "snapshot": snapshot(board), "kicadVersion": pcbnew.Version()}
        elif cmd == "netclasses":
            res = netclasses(*args)
        elif cmd == "ripup":
            res = ripup(*args)
        elif cmd == "dsn":
            res = dsn(*args)
        elif cmd == "ses":
            res = ses(*args)
        else:
            res = fill(*args)
    except Exception as e:  # report, never a bare traceback on stdout
        import traceback
        sys.stderr.write(traceback.format_exc())
        emit({"ok": False, "error": "%s: %s" % (type(e).__name__, e)}, 1)
    emit(res, 0 if res.get("ok") else 1)


if __name__ == "__main__":
    main(sys.argv)
