package app

// `pcbpilot pcb layout-plan` is intentionally offline. The constructor receives
// no appConfig/window, so this command cannot dispatch an editor action by
// accident. It consumes a measured `pcb dump` plus explicit layout relations and
// writes reviewable candidate bundles.

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

func newPcbLayoutPlanCmd(stdout, stderr io.Writer) *cobra.Command {
	var fromPath, boardPath, moduleID, outDir string
	var maxCandidates int
	c := &cobra.Command{
		Use:   "layout-plan",
		Short: "Generate measured module placement candidates offline (no editor writes)",
		Long: `Generate up to three distinct placement candidates for ONE declared module.

The layout input declares module membership, exact pad ownership, fixed axes,
allowed angles, board-edge intent and keepouts. --board must be a measured JSON
snapshot from 'pcbpilot pcb dump'; footprint anchors are the only write coordinates,
while bboxes and pad centers are measurement data. The planner transforms anchors,
bbox corners and pads together, so asymmetric footprint origins remain correct.

This command is pure local computation: it never connects to EasyEDA and never
moves a component. Each candidate contains factual distances/clearances, names
the closest internal, external-component and keepout object pairs, includes an SVG
preview, and provides a typed 'pcbpilot apply' playbook. It emits no aggregate score and
does not choose a winner. Locked/fixed axes, board bounds, overlap and declared
keepouts only decide geometric legality. A generated playbook is bound to the
primitive IDs in the supplied board dump; take a fresh dump before applying stale
output.

crystal-guard supports search.offsetsMil relative to owner signal-pad midpoint
alignment (bottom owner: yMil <= 0), and search.crystalOffsets with maxXMil,
maxAwayMil and positive stepMil. Bounded grid, measured obstacle-edge and matching
pad-alignment seeds regenerate all external routes/guards/regions/vias. Each gap
prefers less away distance, then less lateral movement; no aggregate score.
More than 4096 offset seeds per gap/rotation fails explicitly. Zero candidates
means this finite search failed, not that every possible placement is impossible.`,
		Example: `  pcbpilot pcb dump --out board.json
  pcbpilot pcb layout-plan --from layout.json --board board.json \
    --module rgb-led --candidates 3 --out candidates/`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if fromPath == "" || boardPath == "" || moduleID == "" || outDir == "" {
				return fmt.Errorf("--from, --board, --module and --out are required")
			}
			if maxCandidates < 1 || maxCandidates > 3 {
				return fmt.Errorf("--candidates must be between 1 and 3")
			}
			layoutRaw, err := os.ReadFile(fromPath)
			if err != nil {
				return fmt.Errorf("read layout input: %w", err)
			}
			boardRaw, err := os.ReadFile(boardPath)
			if err != nil {
				return fmt.Errorf("read board snapshot: %w", err)
			}
			input, err := decodePCBLayoutPlanInput(layoutRaw)
			if err != nil {
				return err
			}
			boardFile, err := os.Open(boardPath)
			if err != nil {
				return err
			}
			snap, loadErr := loadBoardSnapshotFile(boardFile)
			closeErr := boardFile.Close()
			if loadErr != nil {
				return loadErr
			}
			if closeErr != nil {
				return closeErr
			}

			rep, planErr := planPCBLayoutModule(input, snap, moduleID, maxCandidates)
			rep.LayoutSHA256 = sha256String(layoutRaw)
			rep.BoardSHA256 = sha256String(boardRaw)
			rep.BoardSemanticSHA256 = snap.SemanticSHA256
			for i := range rep.Candidates {
				rep.Candidates[i].Apply.Meta.Description = fmt.Sprintf(
					"Generated by pcbpilot pcb layout-plan; footprint-anchor coordinates; boardSha256=%s; layoutSha256=%s; boardSemanticSha256=%s; hashSemantic=sha256(raw-file-bytes); semanticHashExcludes=capturedAt,semanticSha256",
					rep.BoardSHA256, rep.LayoutSHA256, rep.BoardSemanticSHA256,
				)
			}
			if err := writePCBLayoutCandidateBundle(outDir, input, snap, &rep); err != nil {
				if planErr != nil {
					return fmt.Errorf("%v; write diagnostic bundle: %w", planErr, err)
				}
				return err
			}
			fmt.Fprintf(stderr, "layout-plan: %s → %s\n", rep.Summary, outDir)
			manifest := filepath.Join(outDir, "manifest.json")
			fmt.Fprintln(stdout, manifest)
			return planErr
		},
	}
	c.Flags().StringVar(&fromPath, "from", "", "layout intent JSON (schemaVersion 1 placement, schemaVersion 2 legacy module, or schemaVersion 3 routing/reflow; mil, footprint-anchor)")
	c.Flags().StringVar(&boardPath, "board", "", "measured board JSON from `pcbpilot pcb dump`")
	c.Flags().StringVar(&moduleID, "module", "", "one module id from the layout input")
	c.Flags().IntVar(&maxCandidates, "candidates", 3, "maximum distinct legal candidates to emit (1..3)")
	c.Flags().StringVar(&outDir, "out", "", "candidate output directory (manifest, JSON, apply playbook and SVG)")
	return c
}

func sha256String(raw []byte) string {
	s := sha256.Sum256(raw)
	return hex.EncodeToString(s[:])
}

func writePCBLayoutCandidateBundle(dir string, input pcbLayoutPlanInput, snap *boardSnapshot, rep *pcbLayoutPlanReport) error {
	cleanDir := filepath.Clean(dir)
	parent := filepath.Dir(cleanDir)
	baseName := filepath.Base(cleanDir)
	if err := os.MkdirAll(parent, 0o755); err != nil {
		return fmt.Errorf("create output parent: %w", err)
	}
	tmpDir, err := os.MkdirTemp(parent, "."+baseName+".tmp-")
	if err != nil {
		return fmt.Errorf("create temporary output directory: %w", err)
	}
	defer os.RemoveAll(tmpDir)
	if err := writePCBLayoutCandidateBundleContents(tmpDir, input, snap, rep); err != nil {
		return err
	}
	backup := tmpDir + ".old"
	hadOld := false
	if _, err := os.Lstat(cleanDir); err == nil {
		if err := os.Rename(cleanDir, backup); err != nil {
			return fmt.Errorf("stage old output directory: %w", err)
		}
		hadOld = true
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("inspect output directory: %w", err)
	}
	if err := os.Rename(tmpDir, cleanDir); err != nil {
		if hadOld {
			_ = os.Rename(backup, cleanDir)
		}
		return fmt.Errorf("replace output directory: %w", err)
	}
	if hadOld {
		if err := os.RemoveAll(backup); err != nil {
			return fmt.Errorf("remove replaced output directory: %w", err)
		}
	}
	return nil
}

func writePCBLayoutCandidateBundleContents(dir string, input pcbLayoutPlanInput, snap *boardSnapshot, rep *pcbLayoutPlanReport) error {
	for i := range rep.Candidates {
		cand := &rep.Candidates[i]
		base := cand.ID
		cand.Files = map[string]string{
			"candidate": base + ".json",
			"apply":     base + ".apply.json",
			"preview":   base + ".svg",
		}
		if cand.Bundle != nil {
			cand.Files["localPreview"] = base + ".local.svg"
			cand.Files["comparisonPreview"] = base + ".compare.svg"
		}
		applyBlob, err := json.MarshalIndent(cand.Apply, "", "  ")
		if err != nil {
			return err
		}
		cand.ApplySHA256 = sha256String(append(applyBlob, '\n'))
		blob, err := json.MarshalIndent(cand, "", "  ")
		if err != nil {
			return err
		}
		if err := writeAtomic(filepath.Join(dir, cand.Files["candidate"]), append(blob, '\n')); err != nil {
			return err
		}
		if err := writeAtomic(filepath.Join(dir, cand.Files["apply"]), append(applyBlob, '\n')); err != nil {
			return err
		}
		var svgFile *os.File
		tmp := filepath.Join(dir, "."+base+".svg.tmp")
		if svgFile, err = os.Create(tmp); err != nil {
			return err
		}
		renderErr := renderPCBLayoutCandidateSVG(svgFile, snap, *cand, input.Keepouts)
		closeErr := svgFile.Close()
		if renderErr != nil {
			_ = os.Remove(tmp)
			return renderErr
		}
		if closeErr != nil {
			_ = os.Remove(tmp)
			return closeErr
		}
		if err := os.Rename(tmp, filepath.Join(dir, cand.Files["preview"])); err != nil {
			_ = os.Remove(tmp)
			return err
		}
		if cand.Bundle != nil {
			for key, mode := range map[string]string{"localPreview": "local", "comparisonPreview": "compare"} {
				tmp = filepath.Join(dir, "."+cand.Files[key]+".tmp")
				if svgFile, err = os.Create(tmp); err != nil {
					return err
				}
				renderErr = renderPCBLayoutModuleSVG(svgFile, snap, *cand, mode)
				closeErr = svgFile.Close()
				if renderErr != nil {
					_ = os.Remove(tmp)
					return renderErr
				}
				if closeErr != nil {
					_ = os.Remove(tmp)
					return closeErr
				}
				if err := os.Rename(tmp, filepath.Join(dir, cand.Files[key])); err != nil {
					_ = os.Remove(tmp)
					return err
				}
			}
		}
	}
	blob, err := json.MarshalIndent(rep, "", "  ")
	if err != nil {
		return err
	}
	return writeAtomic(filepath.Join(dir, "manifest.json"), append(blob, '\n'))
}

func writeAtomic(path string, data []byte) error {
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}
