package app

// kicad_route_tracemaker.go — TraceMaker (github.com/zhuangzard/tracemaker-pcbpilot,
// a modified build of the open-source KiCad router) as the second routing
// backend of `kicad route`. It reads the classed .kicad_pcb (+ .kicad_pro /
// .kicad_dru) directly and writes a routed .kicad_pcb, so no DSN / SES step is
// involved. Like fastroute it is only ever run as a separate process found on
// disk; its result enters the same routeResult every gate consumes.

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/zhuangzard/pcbpilot/internal/kicad"
)

const tracemakerInstallHint = "tracemaker not found: set --tracemaker-bin or $TRACEMAKER_BIN, install the pcbpilot build to ~/.pcbpilot/tracemaker/current (see docs/kicad/PARITY.md), or put it on PATH"

// resolveTracemaker finds the tracemaker executable: explicit flag, then
// $TRACEMAKER_BIN, ~/.pcbpilot/tracemaker/current (a binary or a directory
// holding one) and PATH.
func resolveTracemaker(explicit string) (string, error) {
	for _, p := range []string{explicit, os.Getenv("TRACEMAKER_BIN")} {
		if p == "" {
			continue
		}
		if _, err := os.Stat(p); err != nil {
			return "", fmt.Errorf("tracemaker binary %s: %w", p, err)
		}
		return p, nil
	}
	if home, err := os.UserHomeDir(); err == nil {
		if p, err := filepath.EvalSymlinks(filepath.Join(home, ".pcbpilot", "tracemaker", "current")); err == nil {
			if st, err := os.Stat(p); err == nil {
				if st.IsDir() {
					p = filepath.Join(p, "tracemaker")
				}
				if _, err := os.Stat(p); err == nil {
					return p, nil
				}
			}
		}
	}
	if p, err := exec.LookPath("tracemaker"); err == nil {
		return p, nil
	}
	return "", errors.New(tracemakerInstallHint)
}

// tracemakerOpts are the pcbpilot-side settings of one tracemaker run.
type tracemakerOpts struct {
	bin string
	// timeout is tracemaker's own --time budget (it also picks the lattice
	// pitch: a short budget gives a coarser lattice); 0 = 300 s.
	timeout time.Duration
	threads int
	// hardLimit kills a run that ignores its own budget.
	hardLimit time.Duration
}

func (o tracemakerOpts) budget() time.Duration {
	if o.timeout <= 0 {
		return 300 * time.Second
	}
	return o.timeout
}

type tmNet struct {
	MinWidthMM float64 `json:"min_width_mm,omitempty"`
	NoNeckdown bool    `json:"no_neckdown,omitempty"`
}

type tmPair struct {
	P      string  `json:"p"`
	N      string  `json:"n"`
	GapMM  float64 `json:"gap_mm,omitempty"`
	SkewMM float64 `json:"skew_mm,omitempty"`
}

// tmConstraints is tracemaker's --constraints file (version 1).
type tmConstraints struct {
	Version int              `json:"version"`
	Comment string           `json:"comment"`
	Nets    map[string]tmNet `json:"nets"`
	Pairs   []tmPair         `json:"pairs,omitempty"`
}

func mmOfMil(mil float64) float64 { return math.Round(mil*0.0254*1000) / 1000 }

// tracemakerConstraints turns the intent requirements into tracemaker's
// constraints. A net with an intent minimum below its class width may neck
// down at the pads, to that minimum and no further (min_width_mm — the
// pad-escape zone the intent-widths gate accepts); any other net wider than
// the DSN's floor never necks down (the rule the DSN preparation applies for
// fastroute). Explicit differential pairs carry their gap and skew.
func tracemakerConstraints(reqs map[string]kicad.NetRequirement, floorMil float64, in *designIntent) tmConstraints {
	c := tmConstraints{Version: 1, Comment: "generated by pcbpilot kicad route --router tracemaker", Nets: map[string]tmNet{}}
	names := make([]string, 0, len(reqs))
	for n := range reqs {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		r := reqs[n]
		switch {
		case r.MinMil > 0 && r.MinMil < r.OuterMil-0.01:
			c.Nets[n] = tmNet{MinWidthMM: mmOfMil(r.MinMil)}
		case r.OuterMil > floorMil+0.01:
			c.Nets[n] = tmNet{NoNeckdown: true}
		}
	}
	if in == nil {
		return c
	}
	seen := map[string]bool{}
	for _, name := range in.sortedNetNames() {
		n := in.Nets[name]
		if n.DiffPair == "" || in.Nets[n.DiffPair] == nil {
			continue
		}
		a, b := name, n.DiffPair
		if b < a {
			a, b = b, a
		}
		if seen[a+"|"+b] {
			continue
		}
		seen[a+"|"+b] = true
		p := tmPair{P: a, N: b}
		if n.PairGapMil > 0 {
			p.GapMM = mmOfMil(n.PairGapMil)
		}
		if n.MaxSkewMil > 0 {
			p.SkewMM = mmOfMil(n.MaxSkewMil)
		}
		c.Pairs = append(c.Pairs, p)
	}
	return c
}

func tracemakerArgs(o tracemakerOpts, in, out, constraints, report string) []string {
	args := []string{"route", in, "-o", out, "--constraints", constraints, "--priority-order-only", "--soft-zones",
		"--time", strconv.FormatFloat(o.budget().Seconds(), 'f', -1, 64), "--no-kb", "--json", report}
	if o.threads > 0 {
		args = append(args, "--threads", strconv.Itoa(o.threads))
	}
	return args
}

// tmReport is the part of tracemaker's --json summary pcbpilot reads.
type tmReport struct {
	Connections int     `json:"connections"`
	Routed      int     `json:"routed"`
	Seconds     float64 `json:"seconds"`
	Blocked     int     `json:"blocked"`
	Unrouted    []struct {
		Net     string `json:"net"`
		From    string `json:"from"`
		To      string `json:"to"`
		Blocked bool   `json:"blocked"`
		Reason  string `json:"reason"`
	} `json:"unrouted"`
	TracksBelowMinWidthNets int `json:"tracks_below_min_width_nets"`
}

func readTracemakerReport(path string) (*tmReport, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var r tmReport
	if err := json.Unmarshal(data, &r); err != nil {
		return nil, fmt.Errorf("parse tracemaker report %s: %w", path, err)
	}
	if r.Connections <= 0 {
		return nil, fmt.Errorf("tracemaker report %s has no connection count", path)
	}
	return &r, nil
}

// tracemakerResult maps a tracemaker report to the router-agnostic result.
// Fixable stays 0: tracemaker does not report violations, KiCad's DRC gate
// is the judge.
func tracemakerResult(rep *tmReport, args []string, version, sha, board, reportPath string) *routeResult {
	res := &routeResult{Router: "tracemaker", Version: version, PatchSHA: sha, Args: args, Board: board, Report: reportPath,
		UnroutedCount: len(rep.Unrouted), Seconds: rep.Seconds}
	if res.UnroutedCount == 0 && rep.Routed < rep.Connections {
		res.UnroutedCount = rep.Connections - rep.Routed
	}
	for _, u := range rep.Unrouted {
		c := routeConn{Net: u.Net, From: u.From, To: u.To}
		res.Unrouted = append(res.Unrouted, c)
		if u.Blocked {
			res.Blocked = append(res.Blocked, c)
		}
	}
	return res
}

// runTracemaker routes `in` (a classed board with its .kicad_pro / .kicad_dru
// beside it) into `out`. The run is killed when ctx ends.
func runTracemaker(ctx context.Context, o tracemakerOpts, in, out, constraints, report string, stderr io.Writer) (*routeResult, error) {
	_ = os.Remove(report)
	_ = os.Remove(out)
	args := tracemakerArgs(o, in, out, constraints, report)
	fmt.Fprintf(stderr, "tracemaker: %s %s\n", o.bin, strings.Join(args, " "))
	limit := o.hardLimit
	if limit <= 0 {
		limit = o.budget()*3 + 5*time.Minute
	}
	rctx, cancel := context.WithTimeout(ctx, limit)
	defer cancel()
	cmd := exec.CommandContext(rctx, o.bin, args...)
	cmd.Stdout, cmd.Stderr = stderr, stderr
	cmd.WaitDelay = 10 * time.Second
	start := time.Now()
	err := cmd.Run()
	if ctx.Err() != nil {
		return nil, ctx.Err()
	}
	if err != nil {
		return nil, fmt.Errorf("tracemaker: %w", err)
	}
	if _, serr := os.Stat(out); serr != nil {
		return nil, fmt.Errorf("tracemaker wrote no board %s", out)
	}
	rep, err := readTracemakerReport(report)
	if err != nil {
		return nil, err
	}
	if rep.Seconds <= 0 {
		rep.Seconds = time.Since(start).Seconds()
	}
	version := ""
	if vb, err := exec.Command(o.bin, "version").Output(); err == nil {
		version = strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(string(vb)), "tracemaker"))
	}
	return tracemakerResult(rep, args, version, executableSHA256(o.bin), out, report), nil
}
