//go:build stress

package app

// stress_hs_test.go — the high-speed stress suite (`make stress-hs`).
//
// Every case under testdata/stress/hs/<case>/ (generated by gen.py: a
// connectivity + values + product spec + a board with realistic footprints
// + expect.json derived by hand) runs the full OFFLINE chain through the
// real CLI, in-process:
//
//	intent derive → pcb rules plan (planIntentRules on the captured host
//	default rule snapshot) → pcb auto run --intent (route-only on the given
//	placement, and --place) → SI evaluation against expect.json.
//
// The daemon is never contacted (--ports points at an unused port; every
// input is a file). Results go to $STRESS_HS_OUT (default
// $TMPDIR/pcbpilot-stress-hs): per case intent.json / plan.json /
// report.md / preview.svg and summary.md for the whole run.
//
// Env: STRESS_HS_CASE=<case> runs one case; STRESS_HS_MODES=route,place;
// STRESS_HS_TIMEOUT=2m routing budget; STRESS_HS_SEED=<n> placement seed
// of the place mode (default 1; sweep seeds to compare placer changes);
// STRESS_HS_REAL=0 skips the rk3568/k230 real-board pass.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/zhuangzard/pcbpilot/pkg/intent"
	"github.com/zhuangzard/pcbpilot/pkg/pcbauto"
)

const stressHSDir = "testdata/stress/hs"

type hsPairExpect struct {
	P, N         string
	Interface    string  `json:"interface"`
	Ohm          float64 `json:"ohm"`
	WidthMil     float64 `json:"widthMil"`
	GapMil       float64 `json:"gapMil"`
	MaxSkewMil   float64 `json:"maxSkewMil"`
	MaxVias      int     `json:"maxVias"`
	Group        string  `json:"group"`
	Uncontrolled bool    `json:"uncontrolled"`
}

type hsExpect struct {
	Case   string         `json:"case"`
	Layers int            `json:"layers"`
	Pairs  []hsPairExpect `json:"pairs"`
	Single *struct {
		Ohm      float64  `json:"ohm"`
		WidthMil float64  `json:"widthMil"`
		Nets     []string `json:"nets"`
	} `json:"singleEnded"`
	Groups []struct {
		Name   string  `json:"name"`
		Units  int     `json:"units"`
		TolMil float64 `json:"tolMil"`
	} `json:"groups"`
	ViaBudget map[string]int `json:"viaBudget"`
	ACCaps    [][2]string    `json:"acCaps"`
	Must      []string       `json:"findingsMust"`
	MustNot   []string       `json:"findingsMustNot"`
	SIMust    []string       `json:"siMust"`
	Negative  bool           `json:"negative"`
	Isolation *struct {
		DomainNet          string   `json:"domainNet"`
		Insulation         string   `json:"insulation"`
		RequiredWithstandV float64  `json:"requiredWithstandV"`
		ClearanceMm        float64  `json:"clearanceMm"`
		CreepageMm         float64  `json:"creepageMm"`
		Bridges            []string `json:"bridges"`
	} `json:"isolation"`
	Route struct {
		MinCompletion        float64 `json:"minCompletion"`
		MaxDRC               int     `json:"maxDRC"`
		MaxSplitCrossings    int     `json:"maxSplitCrossings"`
		MaxIsolationFindings *int    `json:"maxIsolationFindings"`
	} `json:"route"`
}

// hsCheck is one row of the verdict: expected vs got.
type hsCheck struct {
	Stage, Name, Want, Got string
	Pass                   bool
}

type hsRun struct {
	checks []hsCheck
}

func (r *hsRun) add(stage, name string, pass bool, want, got string, a ...any) {
	r.checks = append(r.checks, hsCheck{Stage: stage, Name: name, Want: want, Got: fmt.Sprintf(got, a...), Pass: pass})
}

func (r *hsRun) failed() []hsCheck {
	var out []hsCheck
	for _, c := range r.checks {
		if !c.Pass {
			out = append(out, c)
		}
	}
	return out
}

func within(got, want, frac float64) bool {
	return want == 0 && got == 0 || math.Abs(got-want) <= frac*math.Abs(want)+1e-9
}

func stressOut(t *testing.T) string {
	d := os.Getenv("STRESS_HS_OUT")
	if d == "" {
		d = filepath.Join(os.TempDir(), "pcbpilot-stress-hs")
	}
	if err := os.MkdirAll(d, 0o755); err != nil {
		t.Fatal(err)
	}
	return d
}

// runCLIOffline executes the real root command in-process. The daemon
// ports point at an unused port so a live path can never reach an editor.
func runCLIOffline(args ...string) (string, string, error) {
	var stdout, stderr bytes.Buffer
	root := newRootCmd(&stdout, &stderr)
	root.SetOut(&stderr)
	root.SetErr(&stderr)
	root.SetArgs(append([]string{"--host", "127.0.0.1", "--ports", "9-9"}, args...))
	err := root.Execute()
	return stdout.String(), stderr.String(), err
}

func stressTimeout() string {
	if v := os.Getenv("STRESS_HS_TIMEOUT"); v != "" {
		return v
	}
	return "2m"
}

func TestStressHS(t *testing.T) {
	if testing.Short() {
		t.Skip("stress suite")
	}
	entries, err := os.ReadDir(stressHSDir)
	if err != nil {
		t.Fatal(err)
	}
	out := stressOut(t)
	modes := []string{"route", "place"}
	if m := os.Getenv("STRESS_HS_MODES"); m != "" {
		modes = strings.Split(m, ",")
	}
	var summary bytes.Buffer
	fmt.Fprintf(&summary, "# pcbpilot high-speed stress suite\n\n%s, routing budget %s, modes %v\n\n", time.Now().Format(time.RFC3339), stressTimeout(), modes)
	fmt.Fprintf(&summary, "| case | checks | failed | verdict |\n|---|---|---|---|\n")
	var details bytes.Buffer
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		name := e.Name()
		if only := os.Getenv("STRESS_HS_CASE"); only != "" && only != name {
			continue
		}
		t.Run(name, func(t *testing.T) {
			r := runStressCase(t, filepath.Join(stressHSDir, name), filepath.Join(out, name), modes)
			bad := r.failed()
			verdict := "PASS"
			if len(bad) > 0 {
				verdict = "FAIL"
			}
			fmt.Fprintf(&summary, "| %s | %d | %d | %s |\n", name, len(r.checks), len(bad), verdict)
			fmt.Fprintf(&details, "\n## %s\n\n| stage | check | expected | got | ok |\n|---|---|---|---|---|\n", name)
			for _, c := range r.checks {
				fmt.Fprintf(&details, "| %s | %s | %s | %s | %s |\n", c.Stage, c.Name, c.Want, c.Got, map[bool]string{true: "✓", false: "✗"}[c.Pass])
			}
			for _, c := range bad {
				t.Errorf("%s / %s: want %s, got %s", c.Stage, c.Name, c.Want, c.Got)
			}
		})
	}
	summary.Write(details.Bytes())
	p := filepath.Join(out, "summary.md")
	_ = os.WriteFile(p, summary.Bytes(), 0o644)
	t.Logf("summary: %s\n%s", p, summary.String())
}

func runStressCase(t *testing.T, dir, out string, modes []string) *hsRun {
	r := &hsRun{}
	if err := os.MkdirAll(out, 0o755); err != nil {
		t.Fatal(err)
	}
	var exp hsExpect
	raw, err := os.ReadFile(filepath.Join(dir, "expect.json"))
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(raw, &exp); err != nil {
		t.Fatal(err)
	}
	// ── 1. intent derive ──────────────────────────────────────────────
	intentPath := filepath.Join(out, "intent.json")
	_, stderr, err := runCLIOffline("intent", "derive", "--connectivity", filepath.Join(dir, "connectivity.json"),
		"--values", filepath.Join(dir, "values.json"), "--spec", filepath.Join(dir, "spec.json"),
		"--models-lib", "../../.agents/skills/pcbpilot/references/power-models.json",
		"--out", intentPath, "--report", filepath.Join(out, "intent.md"))
	if err != nil {
		t.Fatalf("intent derive: %v\n%s", err, stderr)
	}
	iraw, _ := os.ReadFile(intentPath)
	var it intent.Intent
	if err := json.Unmarshal(iraw, &it); err != nil {
		t.Fatal(err)
	}
	checkIntent(r, &it, &exp)
	// ── 2. rules plan ─────────────────────────────────────────────────
	di, err := parseDesignIntent(iraw)
	if err != nil {
		t.Fatalf("rules: %v", err)
	}
	board, err := pcbauto.FromSnapshot(mustRead(t, filepath.Join(dir, "board.json")))
	if err != nil {
		t.Fatal(err)
	}
	var nets []string
	for _, n := range board.Nets() {
		nets = append(nets, n.Name)
	}
	plan := planIntentRules(di, snapshotOf(t, cleanHostConfig(t, nets)), netSet(nets), nil)
	pj, _ := json.MarshalIndent(plan, "", "  ")
	_ = os.WriteFile(filepath.Join(out, "rules-plan.json"), pj, 0o644)
	checkRulesPlan(r, plan, &exp)
	// ── 3. pcb auto run --intent ──────────────────────────────────────
	for _, mode := range modes {
		od := filepath.Join(out, mode)
		args := []string{"pcb", "auto", "run", "--board", filepath.Join(dir, "board.json"), "--intent", intentPath,
			"--out-dir", od, "--no-feedback", "--layers", fmt.Sprint(exp.Layers), "--timeout", stressTimeout()}
		if mode == "place" {
			seed := os.Getenv("STRESS_HS_SEED")
			if seed == "" {
				seed = "1"
			}
			args = append(args, "--place", "--loops", "0", "--seed", seed)
		}
		start := time.Now()
		_, stderr, err := runCLIOffline(args...)
		if err != nil {
			r.add(mode, "pcb auto run", false, "ok", "%v", err)
			t.Logf("%s: %v\n%s", mode, err, stderr)
			continue
		}
		var rep pcbauto.Report
		if err := json.Unmarshal(mustRead(t, filepath.Join(od, "plan.json")), &rep); err != nil {
			t.Fatal(err)
		}
		t.Logf("%s %s: %.0fs\n%s", filepath.Base(dir), mode, time.Since(start).Seconds(), lastLines(stderr, 8))
		checkRoute(r, mode, &rep, &it, &exp, board)
	}
	return r
}

func mustRead(t *testing.T, p string) []byte {
	b, err := os.ReadFile(p)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func lastLines(s string, n int) string {
	ls := strings.Split(strings.TrimSpace(s), "\n")
	if len(ls) > n {
		ls = ls[len(ls)-n:]
	}
	return strings.Join(ls, "\n")
}

func checkIntent(r *hsRun, it *intent.Intent, exp *hsExpect) {
	const st = "intent"
	for _, pe := range exp.Pairs {
		for _, pair := range [][2]string{{pe.P, pe.N}, {pe.N, pe.P}} {
			np := it.Nets[pair[0]]
			if np == nil {
				r.add(st, pair[0], false, "net present", "missing")
				continue
			}
			r.add(st, pair[0]+" pair/interface", np.Role == "diff" && np.DiffPair == pair[1] && np.Interface == pe.Interface,
				fmt.Sprintf("diff ↔ %s, %s", pair[1], pe.Interface), "%s ↔ %s, %s", np.Role, np.DiffPair, np.Interface)
			if pair[0] != pe.P {
				continue // dimensions once per pair
			}
			r.add(st, pe.P+" impedance", np.ImpedanceOhm == pe.Ohm, fmt.Sprintf("%.0f Ω", pe.Ohm), "%.0f Ω", np.ImpedanceOhm)
			r.add(st, pe.P+" width", within(np.WidthMil.Outer, pe.WidthMil, 0.05), fmt.Sprintf("%.1f mil ±5%%", pe.WidthMil), "%.1f mil", np.WidthMil.Outer)
			r.add(st, pe.P+" gap", within(np.PairGapMil, pe.GapMil, 0.05), fmt.Sprintf("%.1f mil ±5%%", pe.GapMil), "%.1f mil", np.PairGapMil)
			r.add(st, pe.P+" skew/vias", np.MaxSkewMil == pe.MaxSkewMil && np.MaxVias == pe.MaxVias,
				fmt.Sprintf("≤%.0f mil, ≤%d vias", pe.MaxSkewMil, pe.MaxVias), "≤%.0f mil, ≤%d vias", np.MaxSkewMil, np.MaxVias)
			if pe.Group != "" {
				r.add(st, pe.P+" length group", np.LengthGroup == pe.Group, pe.Group, "%s", np.LengthGroup)
			}
		}
	}
	if s := exp.Single; s != nil {
		bad := []string{}
		for _, n := range s.Nets {
			if np := it.Nets[n]; np == nil || !within(np.WidthMil.Outer, s.WidthMil, 0.05) || np.ImpedanceOhm != s.Ohm {
				bad = append(bad, n)
			}
		}
		r.add(st, "single-ended impedance", len(bad) == 0, fmt.Sprintf("%d nets %.0f Ω w %.1f mil", len(s.Nets), s.Ohm, s.WidthMil), "%d off: %s", len(bad), strings.Join(bad, ","))
	}
	groups := map[string][]*intent.NetPlan{}
	gnets := map[string][]string{}
	for _, n := range sortedKeysNP(it.Nets) {
		if np := it.Nets[n]; np.LengthGroup != "" {
			groups[np.LengthGroup] = append(groups[np.LengthGroup], np)
			gnets[np.LengthGroup] = append(gnets[np.LengthGroup], n)
		}
	}
	for _, g := range exp.Groups {
		ms := groups[g.Name]
		units, tol := 0, 0.0
		seen := map[string]bool{}
		for i, np := range ms {
			n := gnets[g.Name][i]
			if seen[n] {
				continue
			}
			seen[n] = true
			if np.DiffPair != "" {
				seen[np.DiffPair] = true
			}
			units++
			tol = math.Max(tol, np.LengthTolMil)
		}
		r.add(st, "group "+g.Name, units == g.Units && tol == g.TolMil, fmt.Sprintf("%d units, ±%.0f mil", g.Units, g.TolMil), "%d units, ±%.0f mil", units, tol)
	}
	kinds := map[string]string{}
	for _, f := range it.Findings {
		kinds[f.Kind] = f.Severity
	}
	for _, k := range exp.Must {
		r.add(st, "finding "+k, kinds[k] != "", "present", "%s", orNone(kinds[k]))
	}
	for _, k := range exp.MustNot {
		r.add(st, "no finding "+k, kinds[k] == "", "absent", "%s", orNone(kinds[k]))
	}
	if iso := exp.Isolation; iso != nil {
		var got *intent.Pair
		for _, p := range it.Pairs {
			got = p
		}
		if got == nil {
			r.add(st, "isolation pair", false, "1 pair", "none")
		} else {
			r.add(st, "isolation grade/withstand", got.Insulation == iso.Insulation && within(got.RequiredWithstandV, iso.RequiredWithstandV, 0.001),
				fmt.Sprintf("%s, %.0f Vpk", iso.Insulation, iso.RequiredWithstandV), "%s, %.0f Vpk", got.Insulation, got.RequiredWithstandV)
			r.add(st, "isolation distances", within(got.ClearanceMm, iso.ClearanceMm, 0.01) && within(got.CreepageMm, iso.CreepageMm, 0.01),
				fmt.Sprintf("clr %.2f / creep %.2f mm", iso.ClearanceMm, iso.CreepageMm), "clr %.2f / creep %.2f mm", got.ClearanceMm, got.CreepageMm)
			missing := []string{}
			for _, b := range iso.Bridges {
				if !has(got.Bridges, b) {
					missing = append(missing, b)
				}
			}
			r.add(st, "isolation bridges", len(missing) == 0, strings.Join(iso.Bridges, ","), "%s", strings.Join(got.Bridges, ","))
		}
	}
}

func orNone(s string) string {
	if s == "" {
		return "none"
	}
	return s
}

func has(xs []string, v string) bool {
	for _, x := range xs {
		if x == v {
			return true
		}
	}
	return false
}

func sortedKeysNP(m map[string]*intent.NetPlan) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func checkRulesPlan(r *hsRun, p *intentRulesPlan, exp *hsExpect) {
	const st = "rules"
	r.add(st, "conflicts", len(p.Conflicts) == 0, "0", "%d %v", len(p.Conflicts), p.Conflicts)
	byPos := map[string]intentDiffPairPlan{}
	for _, d := range p.DiffPairs {
		byPos[d.Positive] = d
	}
	for _, pe := range exp.Pairs {
		d, ok := byPos[pe.P]
		r.add(st, "diffPair "+pe.P, ok && d.Negative == pe.N && d.Action == "create" && d.LengthTolMil == pe.MaxSkewMil,
			fmt.Sprintf("+%s −%s create, tol %.0f mil", pe.P, pe.N, pe.MaxSkewMil), "+%s −%s %s, tol %.0f mil", d.Positive, d.Negative, d.Action, d.LengthTolMil)
	}
	lg := map[string]intentLengthGroupPlan{}
	for _, g := range p.LengthGroups {
		lg[g.Name] = g
	}
	for _, g := range exp.Groups {
		got, ok := lg[g.Name]
		r.add(st, "lengthGroup "+g.Name, ok && got.TolMil == g.TolMil, fmt.Sprintf("±%.0f mil", g.TolMil), "present=%v ±%.0f mil (%d pairs)", ok, got.TolMil, got.Pairs)
	}
}

func checkRoute(r *hsRun, mode string, rep *pcbauto.Report, it *intent.Intent, exp *hsExpect, orig *pcbauto.Board) {
	res := rep.Result
	if res == nil || res.Route == nil || rep.SI == nil {
		r.add(mode, "routing result", false, "present", "missing")
		return
	}
	s := res.Route.Stats
	r.add(mode, "completion", s.Completion >= exp.Route.MinCompletion, fmt.Sprintf("≥ %.0f%%", exp.Route.MinCompletion), "%.1f%% (%d/%d)", s.Completion, s.Routed, s.Connections)
	if j := rep.Joint; j != nil && j.PlanePads > 0 {
		r.add(mode, "plane connections", j.PlaneOpen == 0, "0 open", "%d/%d open", j.PlaneOpen, j.PlanePads)
	}
	r.add(mode, "DRC", len(res.DRC.Violations) <= exp.Route.MaxDRC, fmt.Sprintf("≤ %d", exp.Route.MaxDRC), "%d %v", len(res.DRC.Violations), res.DRC.ByKind)
	si := rep.SI
	fk := map[string]int{}
	for _, f := range si.Findings {
		fk[f.Kind]++
	}
	if exp.Negative {
		for _, k := range exp.SIMust {
			r.add(mode, "SI flags "+k, fk[k] > 0, "> 0", "%d", fk[k])
		}
		return
	}
	r.add(mode, "split crossings", fk["split-crossing"] <= exp.Route.MaxSplitCrossings, fmt.Sprintf("≤ %d", exp.Route.MaxSplitCrossings), "%d", fk["split-crossing"])
	r.add(mode, "no-reference", fk["no-reference"] == 0, "0", "%d", fk["no-reference"])
	pairs := map[string]pcbauto.SIPair{}
	for _, p := range si.Pairs {
		pairs[p.P], pairs[p.N] = p, p
	}
	vias := map[string]int{}
	lens := map[string]float64{}
	for _, n := range si.Nets {
		vias[n.Net], lens[n.Net] = n.Vias, n.LengthMil
	}
	width := routedWidths(res.Route)
	padsOf := map[string]int{}
	for _, n := range orig.Nets() {
		padsOf[n.Name] = len(n.Pads)
	}
	open := map[string]bool{}
	for _, u := range res.Route.Unrouted {
		open[u.Net] = true
	}
	for _, pe := range exp.Pairs {
		p, ok := pairs[pe.P]
		inc := ""
		if open[pe.P] || open[pe.N] {
			inc = " — pair incomplete"
		}
		r.add(mode, pe.P+" skew", ok && inc == "" && p.SkewMil <= pe.MaxSkewMil && p.LimitMil == pe.MaxSkewMil,
			fmt.Sprintf("≤ %.0f mil", pe.MaxSkewMil), "%.0f mil (limit %.0f; %.0f/%.0f)%s", p.SkewMil, p.LimitMil, lens[pe.P], lens[pe.N], inc)
		r.add(mode, pe.P+" vias", vias[pe.P] <= pe.MaxVias && vias[pe.N] <= pe.MaxVias, fmt.Sprintf("≤ %d", pe.MaxVias), "%d/%d", vias[pe.P], vias[pe.N])
		np := it.Nets[pe.P]
		if np != nil {
			// The impedance width must be the body of the route; a neck
			// to the fab minimum is legal only at the pads (≤ 60 mil per
			// pad of the net) — a pair necked along its run is off target.
			f, necked := width[pe.P].fracAt(np.WidthMil.Outer), width[pe.P].below(np.WidthMil.Outer)
			allow := 60 * float64(padsOf[pe.P])
			r.add(mode, pe.P+" routed width", f >= 0.6 || necked <= allow, fmt.Sprintf("%.1f mil body (≥ 60%% or necks ≤ %.0f mil)", np.WidthMil.Outer, allow), "%.0f%%, necked %.0f mil (%s)", f*100, necked, width[pe.P].String())
		}
	}
	if b := exp.ViaBudget; b != nil {
		for g, max := range b {
			worst, who := 0, ""
			for n, np := range it.Nets {
				if np.LengthGroup == g && vias[n] > worst {
					worst, who = vias[n], n
				}
			}
			r.add(mode, "via budget "+g, worst <= max, fmt.Sprintf("≤ %d", max), "%d (%s)", worst, who)
		}
	}
	sg := map[string]pcbauto.SIGroup{}
	for _, g := range si.Groups {
		sg[g.Name] = g
	}
	for _, g := range exp.Groups {
		got, ok := sg[g.Name]
		r.add(mode, "group "+g.Name, ok && got.Unrouted == 0 && got.SpreadMil <= g.TolMil && got.TolMil == g.TolMil,
			fmt.Sprintf("spread ≤ %.0f mil", g.TolMil), "present=%v spread %.0f mil (%.0f…%.0f, tol %.0f, %d units, %d unrouted)", ok, got.SpreadMil, got.MinMil, got.MaxMil, got.TolMil, len(got.Units), got.Unrouted)
	}
	if exp.Route.MaxIsolationFindings != nil {
		iso := res.Isolation
		n := -1
		moats := 0
		if iso != nil {
			n, moats = len(iso.Findings), len(iso.Moats)
		}
		r.add(mode, "isolation findings", n >= 0 && n <= *exp.Route.MaxIsolationFindings, fmt.Sprintf("≤ %d", *exp.Route.MaxIsolationFindings), "%d (no-pour regions %d)", n, moats)
		r.add(mode, "no-pour under barrier", moats > 0, "≥ 1 no-pour region", "%d", moats)
	}
	pos := map[string]pcbauto.Point{}
	for _, p := range orig.Parts {
		pos[p.Ref] = p.Pos
	}
	if rep.Placement != nil {
		for _, p := range rep.Placement.Placements {
			pos[p.Ref] = pcbauto.Point{X: p.X, Y: p.Y}
		}
	}
	for _, cc := range exp.ACCaps {
		d := pos[cc[0]].Dist(pos[cc[1]])
		r.add(mode, "AC caps "+cc[0]+"/"+cc[1]+" side by side", d <= 60.5, "≤ 60 mil apart", "%.1f mil", d)
	}
}

// widthHist is a net's routed length per track width.
type widthHist map[float64]float64

func (h widthHist) fracAt(w float64) float64 {
	tot, at := 0.0, 0.0
	for k, l := range h {
		tot += l
		if k >= w-0.05 {
			at += l
		}
	}
	if tot == 0 {
		return 0
	}
	return at / tot
}

func (h widthHist) below(w float64) float64 {
	s := 0.0
	for k, l := range h {
		if k < w-0.05 {
			s += l
		}
	}
	return s
}

func (h widthHist) String() string {
	var ks []float64
	for k := range h {
		ks = append(ks, k)
	}
	sort.Float64s(ks)
	var s []string
	for _, k := range ks {
		s = append(s, fmt.Sprintf("%.1f:%.0f", k, h[k]))
	}
	return strings.Join(s, " ")
}

func routedWidths(rr *pcbauto.RouteResult) map[string]widthHist {
	out := map[string]widthHist{}
	for _, t := range rr.Tracks {
		if out[t.Net] == nil {
			out[t.Net] = widthHist{}
		}
		out[t.Net][math.Round(t.Width*100)/100] += t.A.Dist(t.B)
	}
	return out
}

// TestStressHSRealBoards derives intent from the PCB pads of the real
// high-speed fixtures (no schematic available) and routes them with it,
// reporting the HS findings. Informational: it fails only when the chain
// itself errors.
func TestStressHSRealBoards(t *testing.T) {
	if testing.Short() || os.Getenv("STRESS_HS_REAL") == "0" {
		t.Skip("real-board pass")
	}
	out := stressOut(t)
	for _, name := range []string{"lckfb-rk3568-4layer", "lckfb-k230-canmv"} {
		if only := os.Getenv("STRESS_HS_CASE"); only != "" && only != name {
			continue
		}
		t.Run(name, func(t *testing.T) {
			od := filepath.Join(out, name)
			_ = os.MkdirAll(od, 0o755)
			board := filepath.Join("testdata/boards", name+".json")
			ip := filepath.Join(od, "intent.json")
			_, stderr, err := runCLIOffline("intent", "derive", "--board", board, "--models-lib", "../../.agents/skills/pcbpilot/references/power-models.json",
				"--out", ip, "--report", filepath.Join(od, "intent.md"))
			if err != nil {
				t.Fatalf("intent derive --board: %v\n%s", err, stderr)
			}
			t.Log(lastLines(stderr, 3))
			var it intent.Intent
			_ = json.Unmarshal(mustRead(t, ip), &it)
			b, _ := pcbauto.FromSnapshot(mustRead(t, board))
			start := time.Now()
			timeout := os.Getenv("STRESS_HS_REAL_TIMEOUT")
			if timeout == "" {
				timeout = "4m"
			}
			_, stderr, err = runCLIOffline("pcb", "auto", "run", "--board", board, "--intent", ip, "--out-dir", filepath.Join(od, "route"),
				"--no-feedback", "--layers", fmt.Sprint(b.CopperLayers), "--timeout", timeout)
			if err != nil {
				t.Fatalf("pcb auto run --intent: %v\n%s", err, stderr)
			}
			var rep pcbauto.Report
			if err := json.Unmarshal(mustRead(t, filepath.Join(od, "route", "plan.json")), &rep); err != nil {
				t.Fatal(err)
			}
			t.Logf("%.0fs\n%s", time.Since(start).Seconds(), lastLines(stderr, 6))
			var md bytes.Buffer
			writeRealHS(&md, name, &it, &rep)
			_ = os.WriteFile(filepath.Join(od, "hs-findings.md"), md.Bytes(), 0o644)
			t.Log(md.String())
		})
	}
}

func writeRealHS(w *bytes.Buffer, name string, it *intent.Intent, rep *pcbauto.Report) {
	si := rep.SI
	s := rep.Result.Route.Stats
	fmt.Fprintf(w, "# %s — intent derive --board + pcb auto run --intent\n\n", name)
	ifaces := map[string]int{}
	for _, np := range it.Nets {
		if np.Interface != "" {
			ifaces[np.Interface]++
		}
	}
	fmt.Fprintf(w, "HS nets by interface: %v\n\n", ifaces)
	fmt.Fprintf(w, "routing: %.1f%% (%d/%d), vias %d+%d, DRC %d, tuned %d\n\n", s.Completion, s.Routed, s.Connections, s.Vias, s.FanoutVias, len(rep.Result.DRC.Violations), s.Tuned)
	fk := map[string]int{}
	for _, f := range si.Findings {
		fk[f.Kind]++
	}
	fmt.Fprintf(w, "SI: %d HS nets, %d pairs measured, %d groups; findings %v\n\n", len(si.Nets), len(si.Pairs), len(si.Groups), fk)
	over := 0
	fmt.Fprintf(w, "| pair | skew mil | limit |\n|---|---|---|\n")
	for _, p := range si.Pairs {
		if p.SkewMil > p.LimitMil {
			over++
			fmt.Fprintf(w, "| %s/%s | %.0f | %.0f |\n", p.P, p.N, p.SkewMil, p.LimitMil)
		}
	}
	fmt.Fprintf(w, "\n%d of %d pairs over their intra-pair limit\n\n| group | units | unrouted | min | max | spread | tol |\n|---|---|---|---|---|---|---|\n", over, len(si.Pairs))
	for _, g := range si.Groups {
		fmt.Fprintf(w, "| %s | %d | %d | %.0f | %.0f | %.0f | %.0f |\n", g.Name, len(g.Units), g.Unrouted, g.MinMil, g.MaxMil, g.SpreadMil, g.TolMil)
	}
	unr := map[string]int{}
	for _, u := range rep.Result.Route.Unrouted {
		if np := it.Nets[u.Net]; np != nil && np.Interface != "" {
			unr[np.Interface]++
		}
	}
	fmt.Fprintf(w, "\nunrouted HS connections by interface: %v\n", unr)
}
